"""Per-job chat endpoint backend.

Answers user follow-up questions about a *completed* takeoff job, grounded in
the structured JSON output already saved to R2. Read-only — does not re-process
the source PDFs.

The result JSON is injected into the system prompt with prompt caching enabled,
so repeat questions on the same job hit the Anthropic cache (~10% of input price)
for the first 5 minutes after the initial question.
"""
import json
import logging
from typing import Any, Dict, List

import anthropic

from config import CLAUDE_API_KEY

logger = logging.getLogger(__name__)

MODEL = "claude-sonnet-4-6"
MAX_TOKENS = 4096
MAX_HISTORY_TURNS = 20
MAX_RESULT_BYTES = 500_000

SYSTEM_PROMPT_HEADER = (
    "You answer questions about a completed painting takeoff generated by an "
    "automated estimator. The user is a contractor reviewing the proposal — "
    "answer concisely, like a knowledgeable colleague.\n\n"
    "Ground every answer in the JSON below. If a value, room, or item isn't "
    "there, say so plainly — never estimate, infer from outside knowledge, or "
    "fabricate numbers. Reference rooms by name and floor when relevant. "
    "Money in dollars; areas in sqft or LF.\n\n"
    "Takeoff JSON:\n"
)


def chat_about_job(result_json: Dict[str, Any], history: List[Dict[str, str]]) -> str:
    """Answer a follow-up question about a completed takeoff job.

    Args:
        result_json: The full result dict loaded from the job's output.json in R2.
        history: Conversation history as [{role, content}, ...]. First message
                 must be 'user'; roles must alternate user/assistant.

    Returns:
        The assistant's reply text.
    """
    if not history or history[0].get("role") != "user":
        raise ValueError("history must start with a user message")

    if len(history) > MAX_HISTORY_TURNS * 2:
        history = history[-(MAX_HISTORY_TURNS * 2):]
        if history[0].get("role") != "user":
            history = history[1:]

    result_text = json.dumps(_trim_for_chat(result_json), indent=2, sort_keys=True)
    if len(result_text) > MAX_RESULT_BYTES:
        result_text = result_text[:MAX_RESULT_BYTES] + "\n... [truncated]"

    system = [{
        "type": "text",
        "text": SYSTEM_PROMPT_HEADER + result_text,
        "cache_control": {"type": "ephemeral"},
    }]

    client = anthropic.Anthropic(api_key=CLAUDE_API_KEY)
    response = client.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        system=system,
        messages=history,
    )

    usage = getattr(response, "usage", None)
    if usage is not None:
        logger.info(
            "chat usage input=%s cache_read=%s cache_write=%s output=%s",
            usage.input_tokens,
            getattr(usage, "cache_read_input_tokens", 0) or 0,
            getattr(usage, "cache_creation_input_tokens", 0) or 0,
            usage.output_tokens,
        )

    return next((b.text for b in response.content if b.type == "text"), "")


def _trim_for_chat(result: Dict[str, Any]) -> Dict[str, Any]:
    """Strip page-level extraction blobs that bloat tokens without helping Q&A.

    The aggregated views (`analysis`, `cost_estimate`, `project_info`) cover
    everything chat needs.
    """
    trimmed = dict(result)
    for k in ("page_extractions", "raw_pages", "page_text", "tile_extractions"):
        trimmed.pop(k, None)
    return trimmed
