#!/bin/zsh
# S4 full validation flag set — 2026-08-21
export NIGHTSHIFT_FAILED_SHEET_RETRY=1
export NIGHTSHIFT_FLOOR_FINISH_RECONCILE=1
export NIGHTSHIFT_WINDOW_TRIM_SCOPE=1
export NIGHTSHIFT_WINDOW_SASH_OPS=1
export NIGHTSHIFT_POWER_WASH_ALLOWANCE=1
export NIGHTSHIFT_UNIT_MIX_GATE=1
export NIGHTSHIFT_SCALED_DIM_QUARANTINE=1
export NIGHTSHIFT_LEVEL5_ALLOWANCE=1
export NIGHTSHIFT_SCOPE_SWEEP=1
export NIGHTSHIFT_SWEEP_SCHEDULE_RESCUE=1
export NIGHTSHIFT_WC_SCHEDULE_GATE=1
export NIGHTSHIFT_WC_SCHEDULE_AUTHORITATIVE=1
export NIGHTSHIFT_VME_STARVED_PROMOTE=1
export NIGHTSHIFT_TEMPLATE_INSTANCE_DEDUP=1
export NIGHTSHIFT_DOOR_SOURCE_RECONCILE=1
export NIGHTSHIFT_ROOM_GEOMETRY_SHADOW=1
export NIGHTSHIFT_GEOMETRIC_ROOM_COMPLETION=1
export NIGHTSHIFT_CEILING_ASSUME_PAINTED=1
export NIGHTSHIFT_SEALED_CONCRETE_ALLOWANCE=1
export NIGHTSHIFT_ELEV_PASS_ALL_TYPES=1
cd "$(dirname "$0")/.."
exec .venv/bin/python nsai_batch_2026-08-20/run_batch.py
