#!/bin/zsh
export NIGHTSHIFT_FAILED_SHEET_RETRY=1
export NIGHTSHIFT_FLOOR_FINISH_RECONCILE=1
export NIGHTSHIFT_WINDOW_TRIM_SCOPE=1
export NIGHTSHIFT_UNIT_MIX_GATE=1
export NIGHTSHIFT_SCALED_DIM_QUARANTINE=1
export NIGHTSHIFT_LEVEL5_ALLOWANCE=1
export NIGHTSHIFT_SCOPE_SWEEP=1
export NIGHTSHIFT_VME_STARVED_PROMOTE=1
export NIGHTSHIFT_WC_SCHEDULE_GATE=1
export NIGHTSHIFT_WC_SCHEDULE_AUTHORITATIVE=1
cd "$(dirname "$0")/.."
exec .venv/bin/python nsai_batch_2026-08-20/run_one.py harlem_valley 1
